# Generated by Django 6.0 on 2025-12-16 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MapNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_coordinate', models.IntegerField()),
                ('y_coordinate', models.IntegerField()),
                ('node_type', models.CharField(choices=[('INTERSECTION', 'Road Intersection'), ('HOUSE', 'Property Location'), ('AMENITY', 'Amenity (School/Hospital)')], default='INTERSECTION', max_length=20)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoadSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField(help_text='Distance in meters or grid units')),
                ('end_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_roads', to='maps.mapnode')),
                ('start_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_roads', to='maps.mapnode')),
            ],
        ),
    ]
