# Generated by Django 6.0 on 2025-12-29 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0003_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='floors',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='property',
            name='kitchens',
            field=models.IntegerField(default=1),
        ),
    ]
