# Generated by Django 6.0 on 2025-12-29 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0004_property_description_property_floors_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='area',
        ),
    ]
