# Generated by Django 6.0 on 2026-01-01 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0007_propertyrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyrequest',
            name='request_type',
            field=models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=10),
        ),
        migrations.CreateModel(
            name='SellPropertyDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('location_name', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sell_details', to='listing.propertyrequest')),
            ],
        ),
    ]
