# Generated by Django 6.0 on 2025-12-31 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0007_propertyrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyrequest',
            name='request_type',
            field=models.CharField(choices=[('buy', 'Buy')], max_length=10),
        ),
    ]
