# Generated by Django 6.0 on 2026-01-01 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0008_alter_propertyrequest_request_type_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='propertyrequest',
            name='unique_user_property_request',
        ),
        migrations.RemoveField(
            model_name='sellpropertydetail',
            name='request',
        ),
        migrations.AddField(
            model_name='propertyrequest',
            name='sell_prop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='listing.sellpropertydetail'),
        ),
        migrations.AlterField(
            model_name='propertyrequest',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='listing.property'),
        ),
    ]
