# Generated by Django 6.0 on 2026-01-01 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0008_alter_propertyrequest_request_type'),
        ('listing', '0009_remove_propertyrequest_unique_user_property_request_and_more'),
    ]

    operations = [
    ]
