# Generated by Django 6.0 on 2026-01-01 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0010_merge_20260101_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyrequest',
            name='request_type',
            field=models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=10),
        ),
    ]
