# Generated by Django 6.0 on 2026-01-02 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0011_alter_propertyrequest_request_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='properties/'),
        ),
    ]
