# Generated by Django 6.0 on 2025-12-16 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedBlueprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structure_json', models.JSONField(help_text='The JSON representation of the BSP Tree layout')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LayoutRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My Dream House', max_length=100)),
                ('plot_width', models.IntegerField(help_text='Width in feet')),
                ('plot_length', models.IntegerField(help_text='Length in feet')),
                ('min_room_size', models.IntegerField(default=100, help_text='Minimum sqft for a room')),
                ('complexity_level', models.IntegerField(default=4, help_text='Recursion depth for BSP')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
