# Generated by Django 6.0 on 2025-12-25 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='location_type',
            field=models.CharField(choices=[('property', 'Property'), ('facility', 'Facility')], default='property', max_length=20),
        ),
        migrations.AlterField(
            model_name='connection',
            name='distance',
            field=models.FloatField(editable=False),
        ),
        migrations.AlterField(
            model_name='connection',
            name='from_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_from', to='locations.location'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='to_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_to', to='locations.location'),
        ),
        migrations.AlterUniqueTogether(
            name='connection',
            unique_together={('from_location', 'to_location')},
        ),
    ]
