# Generated by Django 6.0 on 2025-12-27 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_location_location_type_alter_connection_distance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WayPoint',
            fields=[
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='locations.location')),
                ('node_type', models.CharField(choices=[('waypoint', 'Way Point'), ('intersection', 'Intersection'), ('roundabout', 'Roundabout')], default='waypoint', max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='location',
            name='location_type',
            field=models.CharField(choices=[('property', 'Property'), ('facility', 'Facility'), ('way_point', 'Way Point')], default='property', max_length=20),
        ),
    ]
