# Generated by Django 6.0 on 2025-12-29 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_waypoint_alter_location_location_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
