# Generated by Django 6.0 on 2025-12-30 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_alter_location_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='type',
            field=models.CharField(choices=[('school', 'School'), ('hospital', 'Hospital'), ('park', 'Park'), ('mosque', 'Mosque'), ('food', 'Food'), ('airport', 'Airport'), ('police_station', 'Police Station')], max_length=20),
        ),
    ]
