# Generated by Django 6.0 on 2025-12-30 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_alter_facility_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='type',
            field=models.CharField(choices=[('school', 'School'), ('hospital', 'Hospital'), ('park', 'Park'), ('mosque', 'Mosque'), ('food', 'Food'), ('market', 'Market'), ('airport', 'Airport'), ('police', 'Police Station')], max_length=20),
        ),
    ]
